# Generated by Django 4.1.7 on 2023-03-05 17:35

from django.db import migrations, models
import orden.common


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[(orden.common.OrdenEstado['CREADO'], 'CREADO'), (orden.common.OrdenEstado['PAGADO'], 'PAGADO'), (orden.common.OrdenEstado['COMPLETADA'], 'COMPLETADA'), (orden.common.OrdenEstado['CANCELADA'], 'CANCELADA')], default=orden.common.OrdenEstado['CREADO'], max_length=50),
        ),
    ]
