# Generated by Django 4.1.7 on 2023-03-04 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0001_initial'),
        ('orden', '0002_orden_orden_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccionorden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direcciones.dirrecionesenvios'),
        ),
    ]
