# Generated by Django 4.1.7 on 2023-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='fecha_respuesta',
            field=models.DateField(null=True, verbose_name='Respondida en'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='respuesta',
            field=models.TextField(max_length=500, null=True, verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='tipo',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], default='Peticion', max_length=10),
            preserve_default=False,
        ),
    ]
