# Generated by Django 4.1.7 on 2023-02-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaproducto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('tipoPeticion', models.CharField(choices=[('C.C', "'Cédula de ciudadanía"), ('T.I', 'Tarjeta de identidad')], max_length=50)),
            ],
            options={
                'verbose_name': 'Peticion',
                'verbose_name_plural': 'Peticiones',
                'db_table': 'peticion',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.CharField(max_length=20, unique=True, verbose_name='Numero de documento')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('rol', models.CharField(choices=[('1', 'Administrador'), ('2', 'Usuario')], max_length=50, verbose_name='Rol')),
                ('tipoDoc', models.CharField(choices=[('C.C', "'Cédula de ciudadanía"), ('T.I', 'Tarjeta de identidad')], max_length=50, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='StockDisponible',
            field=models.PositiveIntegerField(verbose_name='Stoc kDisponible'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('peticion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peticion', verbose_name='Peticion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario'),
        ),
    ]
