# Generated by Django 4.1.7 on 2023-02-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_peticion_rol_usuario_alter_producto_stockdisponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='tipoPeticion',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Reclamo', 'Reclamo '), ('Peticion', 'Peticion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario'),
        ),
    ]
