# Generated by Django 4.1.7 on 2023-02-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_peticion_tipopeticion_alter_peticion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nit', models.PositiveIntegerField(verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='respuesta',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='InventarioSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario', verbose_name='Inventario')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'InventarioSalida',
                'verbose_name_plural': 'InventariosSalidas',
                'db_table': 'inventarioSalida',
            },
        ),
        migrations.CreateModel(
            name='InventarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario', verbose_name='Inventario')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'InventarioEntrada',
                'verbose_name_plural': 'InventariosEntradas',
                'db_table': 'inventarioEntrada',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precioProducto', models.PositiveIntegerField(verbose_name='Precio del producto')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('iva', models.PositiveIntegerField(verbose_name='iva')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'DetalleVenta',
                'verbose_name_plural': 'DetallesVentas',
                'db_table': 'detalleVentas',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precioProducto', models.PositiveIntegerField(verbose_name='Precio del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('iva', models.PositiveIntegerField(verbose_name='iva')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra', verbose_name='Compra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'DetalleCompra',
                'verbose_name_plural': 'DetallesCompras',
                'db_table': 'detalleCompra',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proeveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor'),
        ),
    ]
