# Generated by Django 4.1.7 on 2023-03-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('creada_en', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Creada por')),
            ],
        ),
    ]
