# Generated by Django 4.1.7 on 2023-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pqr_fecha_respuesta_pqr_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='type',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], default='Peticion', max_length=10),
            preserve_default=False,
        ),
    ]
