# Generated by Django 4.1.7 on 2023-03-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pqr_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqr',
            old_name='type',
            new_name='tipo',
        ),
    ]
