# Generated by Django 4.1.7 on 2023-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_slug'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='productos',
            field=models.ManyToManyField(through='carrito.ProductosCarro', to='core.producto'),
        ),
    ]
