# Generated by Django 4.1.7 on 2023-02-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carrito_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
