# Generated by Django 4.1.7 on 2023-02-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='egundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='user',
            name='primer_apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Primer Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipoDoc',
            field=models.CharField(choices=[('C.C', "'Cédula de ciudadanía"), ('T.I', 'Tarjeta de identidad')], default=1, max_length=50, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
    ]
