# Generated by Django 4.1.7 on 2023-02-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_direccion_user_egundo_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='egundo_apellido',
            new_name='segundo_apellido',
        ),
    ]
